version: '3.9'

services:
  db:
    image: postgres:15
    container_name: postgres_miagenda
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    container_name: miagenda_dental_backend
    build:
      context: .
    command: npm run start:dev
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - '3000:3000'
    depends_on:
      - db
    env_file:
      - .env

volumes:
  postgres_data:
